//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaHuo.ScheduleTask.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string jobname { get; set; }
        public Nullable<int> statusid { get; set; }
        public string groupname { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public bool isrepeat { get; set; }
        public Nullable<int> repeatcoount { get; set; }
        public Nullable<int> interval { get; set; }
        public string cronschedule { get; set; }
        public string assemblyname { get; set; }
        public string @namespace { get; set; }
    }
}
